### ISSUE TITLE
Create REST service for layout management

### ISSUE THREAD

**Issue by pling-scottlogic** [ScottLogic/finos-vuu#25]
### Background
As part of the [layout management ](https://github.com/finos/vuu/issues/333) directive, we want to create a backend service to handle remotely saved layouts.

### Work Required
- Create a backend service to act as a layout management server with Java and Spring Boot
  - Define an API on the service with the following endpoints:
    - `GET` for loading saved layouts
    - `POST` for saving new layouts
    - `PUT` for updating existing layouts
    - `DELETE` for deleting layout
- API contract using openAPI (Good to have. Timebox: 0.5 day)
- Add README: include steps to set up Java environment (see what is already covered by steps for setting up Scala)

**Comment by cfisher-scottlogic** [comment]
Check that unit & integration tests are running in the pipeline by writing a failing test. If running, cool. If not running, create a new ticket to set this up in the pipeline.

**Comment by pling-scottlogic** [comment]
Reminder that we will need another resource for application layouts, [as mentioned here](https://github.com/ScottLogic/finos-vuu/pull/58#discussion_r1342539259). Probably best to raise another ticket for that to avoid scope creep here.

**Comment by cfisher-scottlogic** [comment]
> - ~~Add README: include steps to set up Java environment (see what is already covered by steps for setting up Scala)~~

I've striked this through as I've created a separate ticket for it (#83), as I was likely to forget as part of  this ticket and we can also encompass clientside documentation in that ticket.
