### ISSUE TITLE
Navbar item moving after resizing

### ISSUE THREAD

**Issue by vferraro-scottlogic** [ScottLogic/finos-vuu#45]
![Image](https://user-images.githubusercontent.com/98337074/268687422-0bd6f85e-be52-4875-ab6f-ca49abe99e7a.gif)

### Repro steps:

- open App/ShellWithNewTheme in showcase
- select "My layouts" in Navbar
- zoom in/out

**Comment by pling-scottlogic** [comment]
Fixed by Steve
