### ISSUE TITLE
Storing PNG string in database

### ISSUE THREAD

**Issue by vferraro-scottlogic** [ScottLogic/finos-vuu#75]
### Background
as part of the layout manager feature we have been taking screenshots of the layouts and we are storing them as strings which are very long. We want to investigate what the best way of handling/storing PNGs is.
example length for the PNG string is 13186 characters

### Outcome
- shortlist of options with pros and cons for dealing with screenshots
- meeting for discussing 

### Questions
- format? (i.e. String, Binary)
- compression?
- changes to DTO?
- same format in client side/ local storage?

**Comment by cfisher-scottlogic** [comment]
The simple fix is to add the `@Lob` annotation to the screenshot field on the server side, keeping it as a String for transferal and storage. This has been implemented in #57.

A [new ticket](https://github.com/orgs/ScottLogic/projects/21/views/1?pane=issue&itemId=42163996) has been created off the back of a discussion about possible alternative data formats for generating, transferring and storing the screenshot. It would require too much work to explore those data formats as part of this spike, but could possibly be worth exploring in the future.
