### ISSUE TITLE
LayoutList overflow hidden

### ISSUE THREAD

**Issue by vferraro-scottlogic** [ScottLogic/finos-vuu#91]
### Repro Steps
- save a high number of layouts
- open my layouts 
- scroll to last layout

![Image](https://user-images.githubusercontent.com/98337074/278023124-632b4cf1-4c93-46cc-b3b4-0054c3451b88.gif)

### expected behaviour
all layouts details are visible in "my layouts"

### actual behaviour
last layout details is hidden 

### Notes 
- try changing height to "auto" for <List/>
- see usage of List in examples/ui-controls/List.tsx ListWithinFlexLayout

**Comment by cfisher-scottlogic** [comment]
Can no longer reproduce, I think it must've been fixed upstream already.

**Comment by cfisher-scottlogic** [comment]
I think this has been resolved upstream already as the solution for `auto` on the List height is implemented, and I can no longer reproduce the issue.
